---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 20200506QASD.
--- DateTime: 2021/12/14 15:55
---

require "LuaEntry"

function OnStart()
    LuaEntry.OnStart();
end

function OnUpdate(deltaTime, unscaledDeltaTime)
    LuaEntry.OnUpdate(deltaTime, unscaledDeltaTime);
end

function OnFixedUpdate(deltaTime, unscaledDeltaTime)
    LuaEntry.OnFixedUpdate(deltaTime, unscaledDeltaTime);
end

function OnDestroy()
    LuaEntry.OnDestroy();
end
