---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 20200506QASD.
--- DateTime: 2021/12/14 16:18
---
---Lua入口
---进入的话 初始化一些数据
---其实目前来说require 我还是没怎么看懂

require "LuaDefault"
require "LuaConfig"

require "Common/Alias"
require "Common/Find"

require "Procedure/ProcedureHelp"
require "Procedure/ProcedureLogin"
require "Procedure/ProcedureEntry"

require "UI/LuaFormManager"
require "UI/Form/LoginForm"
require "UI/Form/LoginWindow"
require "UI/Form/RegisterWindow"

LuaEntry = {}

function LuaEntry.OnStart()
   
end

function LuaEntry.OnUpdate(deltaTime, unscaledDeltaTime)
   
end

function LuaEntry.OnFixedUpdate(deltaTime, unscaledDeltaTime)
   
end

function LuaEntry.OnDestroy()
    
end