---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 20200506QASD.
--- DateTime: 2021/12/16 18:20
---

--加载程序集
--全局的程序集

GF = CS.GameFramework
UGF = CS.UnityGameFramework.Runtime
Game = CS.Game

Log = GF.Log
ReferencePool = GF.ReferencePool
Utility = GF.Utility
GameEntry = Game.GameEntry

LuaHelper = Game.LuaHelper
Time = CS.UnityEngine.Time
Vector2 = CS.UnityEngine.Vector2
Vector3 = CS.UnityEngine.Vector3
Color = CS.UnityEngine.Color
GameObject = CS.UnityEngine.GameObject
Matrix4x4 = CS.UnityEngine.Matrix4x4
Quaternion = CS.UnityEngine.Quaternion
String =CS.System.String
Math =CS.UnityEngine.Mathf

