---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 20200506QASD.
--- DateTime: 2022/1/13 14:27
---

--- 关于一些查找方法 TODO

Find = {}
local this = Find

function Find.FindChild(self,childName)
    if self == nil then
        print("查找的self为空")
        return nil
    end
    if childName == nil then
        print("查找的子物体为空")
       return nil 
    end
    local childs = self.transform:Find(childName)
    
end 