---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 20200506QASD.
--- DateTime: 2022/1/12 18:45
---

LoginWindow = {}

local this = LoginWindow
LuaFormManager.FormClassDict["LoginWindow"] = this --这一步很关键把自己给注册进管理器中

local AssetUtility = Game.AssetUtility
local closeBtn

function LoginWindow.OnInit(self)
    closeBtn = self.transform:Find("Popup_Login/Popup/Button_Close"):GetComponent("Button")

    --添加一个默认关闭的方法
    closeBtn.onClick:AddListener(function() self:Close() end)
end

function LoginWindow.OnOpen(cachedTransform, userData)
    
end

function LoginWindow.OnUpdate(elapseSeconds, realElapseSeconds)
    --print("执行LoginPopup Update")
end

function LoginWindow.OnClose()
    
end 
