---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 20200506QASD.
--- DateTime: 2022/1/12 11:06
---

LoginForm = {}

local this = LoginForm
LuaFormManager.FormClassDict["LoginForm"] = this --把自己给注册进管理器中

local AssetUtility = Game.AssetUtility
local loginBtn = nil
local registerBtn = nil
local guestModelBtn = nil

function LoginForm.OnInit(self)
     loginBtn = self.transform:Find("TapToStart/Button_Login"):GetComponent("Button")
     registerBtn = self.transform:Find("TapToStart/Button_Register"):GetComponent("Button")
     guestModelBtn = self.transform:Find("TapToStart/Button_GuestModel"):GetComponent("Button")

     loginBtn.onClick:AddListener(this.OnLoginClick)
     registerBtn.onClick:AddListener(this.OnRegisterClick)
     guestModelBtn.onClick:AddListener(this.OnGuestModelBtnClick)
end

function LoginForm.OnOpen(cachedTransform, userData)
    
end

function LoginForm.OnUpdate(elapseSeconds, realElapseSeconds)
     
end

function LoginForm.OnClose()
     
end 

function LoginForm.OnLoginClick()
     GameEntry.UI:OpenUIForm(AssetUtility.GetUIFormAsset("LoginWindow"),"Window");
end

function LoginForm.OnRegisterClick()
     --GameEntry.UI:OpenUIForm(AssetUtility.GetUIFormAsset("LoginWindow"),"Window");
     print("点击了OnRegisterClick")
end

function LoginForm.OnGuestModelBtnClick()
     --GameEntry.UI:OpenUIForm(AssetUtility.GetUIFormAsset("LoginWindow"),"Window");
     print("点击了OnGuestModelBtnClick")
end
