---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 20200506QASD.
--- DateTime: 2022/1/12 11:27
---
---Lua界面管理器

LuaFormManager = {}

local this = LuaFormManager

-- 每个Form都需要指定在这里
this.FormToLuaNames = 
{
    ["LoginForm"] = "UI/LoginForm",
    ["LoginWindow"] = "UI/LoginWindow",
}

-- 每个Form初始化的时候
-- 需要在每个界面类里面注册在这里 
-- !!!!!!!
this.FormClassDict = {}