---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 20200506QASD.
--- DateTime: 2022/1/13 18:21
---

---注册窗口

RegisterWindow = {}

local this = RegisterWindow
LuaFormManager.FormClassDict["RegisterWindow"] = this --这一步很关键把自己给注册进管理器中

local closeBtn = nil

function RegisterWindow.OnInit(self)
    closeBtn = self.transform:Find("Popup_Signup/Popup/Button_Close"):GetComponent("Button")

    --添加一个默认关闭的方法
    closeBtn.onClick:AddListener(function() self:Close() end)
end

function RegisterWindow.OnOpen(cachedTransform, userData)
    
end

function RegisterWindow.OnClose()

end 