---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 20200506QASD.
--- DateTime: 2021/12/14 16:17
---

local ProcedureMain = class("ProcedureMain")

function ProcedureMain:OnEnter(procedureOwner)
    self.procedureOwner = procedureOwner
    Log.Info("Lua ProcedureMain:OnEnter")
end

local count = 0
function ProcedureMain:OnUpdate(procedureOwner)
    count = count + 1
    Log.Info(count)
end 