---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 20200506QASD.
--- DateTime: 2022/1/11 18:10
---

ProcedureHelp = {}

local this = ProcedureHelp

this.ProcedureName = 
{
    ["ProcedureLogin"] = "Procedure/ProcedureLogin",
}


